// Code generated by MockGen. DO NOT EDIT.
// Regenerate with:
//
//	mockgen -destination=mocks/mock_analytics.go -package=analytics_mocks -typed \
//	  github.com/cli/go-cli-tool/internal/analytics Service,HTTPClient

package analytics_mocks

import (
	io      "io"
	http    "net/http"
	reflect "reflect"

	analytics "github.com/cli/go-cli-tool/internal/analytics"
	gomock    "go.uber.org/mock/gomock"
)

// ---- MockService --------------------------------------------------------

// MockService is a mock of the analytics.Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

type MockServiceMockRecorder struct {
	mock *MockService
}

func NewMockService(ctrl *gomock.Controller) *MockService {
	m := &MockService{ctrl: ctrl}
	m.recorder = &MockServiceMockRecorder{m}
	return m
}

func (m *MockService) EXPECT() *MockServiceMockRecorder { return m.recorder }

func (m *MockService) Disable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disable")
}

func (mr *MockServiceMockRecorder) Disable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockService)(nil).Disable))
}

func (m *MockService) Enable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enable")
}

func (mr *MockServiceMockRecorder) Enable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockService)(nil).Enable))
}

func (m *MockService) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (mr *MockServiceMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockService)(nil).IsEnabled))
}

func (m *MockService) EmitEvent(event analytics.TrackEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitEvent", event)
}

func (mr *MockServiceMockRecorder) EmitEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitEvent",
		reflect.TypeOf((*MockService)(nil).EmitEvent), event)
}

// ---- MockHTTPClient -----------------------------------------------------

// MockHTTPClient is a mock of the analytics.HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	m := &MockHTTPClient{ctrl: ctrl}
	m.recorder = &MockHTTPClientMockRecorder{m}
	return m
}

func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder { return m.recorder }

func (m *MockHTTPClient) Post(url, contentType string, body io.Reader) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url, contentType, body)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockHTTPClientMockRecorder) Post(url, contentType, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post",
		reflect.TypeOf((*MockHTTPClient)(nil).Post), url, contentType, body)
}
