// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cli/go-cli-tool/internal/service (interfaces: SkillService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_skill_service.go -package=service_mocks -typed github.com/cli/go-cli-tool/internal/service SkillService
//

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/cli/go-cli-tool/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillService is a mock of SkillService interface.
type MockSkillService struct {
	ctrl     *gomock.Controller
	recorder *MockSkillServiceMockRecorder
	isgomock struct{}
}

// MockSkillServiceMockRecorder is the mock recorder for MockSkillService.
type MockSkillServiceMockRecorder struct {
	mock *MockSkillService
}

// NewMockSkillService creates a new mock instance.
func NewMockSkillService(ctrl *gomock.Controller) *MockSkillService {
	mock := &MockSkillService{ctrl: ctrl}
	mock.recorder = &MockSkillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillService) EXPECT() *MockSkillServiceMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockSkillService) Install(ctx context.Context, agentName string) ([]service.InstallResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, agentName)
	ret0, _ := ret[0].([]service.InstallResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockSkillServiceMockRecorder) Install(ctx, agentName any) *MockSkillServiceInstallCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockSkillService)(nil).Install), ctx, agentName)
	return &MockSkillServiceInstallCall{Call: call}
}

// MockSkillServiceInstallCall wrap *gomock.Call
type MockSkillServiceInstallCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSkillServiceInstallCall) Return(arg0 []service.InstallResult, arg1 error) *MockSkillServiceInstallCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSkillServiceInstallCall) Do(f func(context.Context, string) ([]service.InstallResult, error)) *MockSkillServiceInstallCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSkillServiceInstallCall) DoAndReturn(f func(context.Context, string) ([]service.InstallResult, error)) *MockSkillServiceInstallCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockSkillService) List(ctx context.Context) ([]service.AgentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]service.AgentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSkillServiceMockRecorder) List(ctx any) *MockSkillServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSkillService)(nil).List), ctx)
	return &MockSkillServiceListCall{Call: call}
}

// MockSkillServiceListCall wrap *gomock.Call
type MockSkillServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSkillServiceListCall) Return(arg0 []service.AgentStatus, arg1 error) *MockSkillServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSkillServiceListCall) Do(f func(context.Context) ([]service.AgentStatus, error)) *MockSkillServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSkillServiceListCall) DoAndReturn(f func(context.Context) ([]service.AgentStatus, error)) *MockSkillServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockSkillService) Remove(ctx context.Context, agentName string) ([]service.RemoveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, agentName)
	ret0, _ := ret[0].([]service.RemoveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockSkillServiceMockRecorder) Remove(ctx, agentName any) *MockSkillServiceRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSkillService)(nil).Remove), ctx, agentName)
	return &MockSkillServiceRemoveCall{Call: call}
}

// MockSkillServiceRemoveCall wrap *gomock.Call
type MockSkillServiceRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSkillServiceRemoveCall) Return(arg0 []service.RemoveResult, arg1 error) *MockSkillServiceRemoveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSkillServiceRemoveCall) Do(f func(context.Context, string) ([]service.RemoveResult, error)) *MockSkillServiceRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSkillServiceRemoveCall) DoAndReturn(f func(context.Context, string) ([]service.RemoveResult, error)) *MockSkillServiceRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
